version: '2'

services:
  db:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  database-data:
