# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='suggestionbox',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
