# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171031_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestionbox',
            options={'verbose_name_plural': 'suggestion boxes'},
        ),
    ]
