# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20171101_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestion_box',
            new_name='topic',
        ),
    ]
